### ISSUE TITLE
Hi! can you make pyfastg available in conda?

### ISSUE THREAD

**Issue by nettanetta** [fedarko/pyfastg#4]
Hi!
I love your parser and use it in my research :) 
Is it possible to make it available via conda also and not just using pip?
thanks!
Netta

**Comment by fedarko** [comment]
I'm glad this is helpful! It should in principle be pretty simple to set this up on conda-forge. I don't have time to get to that now, but I'll try to make time for it soon.

In the interim, I think it should be possible to install this while installing conda dependencies using the method described [here](https://github.com/alexomics/read-paf/issues/9#issuecomment-1148452959).

**Comment by nettanetta** [comment]
It tried it and I think it works! 
thank you :)

**Comment by fedarko** [comment]
pyfastg is now available [through bioconda](https://anaconda.org/bioconda/pyfastg)! The [installation](https://github.com/fedarko/pyfastg#installation) section of the README has more details on how to install pyfastg using conda.

**Comment by nettanetta** [comment]
Great news!
thank you very much
